### ISSUE TITLE
Document the steps

### ISSUE THREAD

**Issue by vikrantk365** [silentsignal/burp-text4shell#1]
Could you document the detailed steps for running this?
I've been able to generate the jar `build/libs/burp-text4shell.jar` but that har in itself doesn't seem to be executable.
Also the project is missing `gradle-wrapper.jar`. Had to use local gradle installation to run the build.

**Comment by dnet** [comment]
Both the README and the GitHub repository description contains the phrase "for Burp Suite", the repo name itself has the prefix `burp-`. If you have Burp Suite, you know what to do with a JAR file, if you don't, you'll have little use for this JAR, as most of the non-text4shell-specific work is done by Burp Suite itself, so it wouldn't be feasible to provide a fallback Burp-less entry point for standalone operation (c.f. our `burp-git-version` plugin). One way of using the plugin within Burp Suite is documented in the README in the section _Single-issue scan_.

As for `gradle-wrapper.jar`, thanks for the nice catch, my local global `.gitignore` must have made me forget adding that.
